version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./:/var/www/html
    depends_on:
      - app
    ports:
      - "8080:80"

  app:
    build: ./
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-AV
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
  db_data:
